ALTER TABLE contests 
ADD COLUMN IF NOT EXISTS poster_url TEXT,
ADD COLUMN IF NOT EXISTS ticket_link TEXT,
ADD COLUMN IF NOT EXISTS details_link TEXT,
ADD COLUMN IF NOT EXISTS location VARCHAR(500),
ADD COLUMN IF NOT EXISTS event_date TIMESTAMP;