ALTER TABLE contests ADD COLUMN IF NOT EXISTS pdf_url TEXT;
ALTER TABLE contests ADD COLUMN IF NOT EXISTS rules TEXT;
ALTER TABLE contests ADD COLUMN IF NOT EXISTS prizes TEXT;
ALTER TABLE contests ADD COLUMN IF NOT EXISTS categories TEXT;